### ISSUE TITLE
Style/ClassAndModuleChildren: Use nested module/class definitions instead of compact style.

### ISSUE THREAD

**Issue by oklahomabigdog** [publicstrategies/rubocop-config#1]
I think this needs to go the way of the white buffalo. 

it enforces this (nested)
``` ruby
class Api
  class V1
    class SomeController
    end
  end
end
```

instead of this (compact)

``` ruby
class Api::V1::SomeController
end
```

Vote for one of the following in the comments below.
- Disabled (allow either way)
- Nested (first example)
- Compact (second example)

**Comment by evanthegrayt** [comment]
I vote Disabled. I don't have a strong preference either way. There are times when both ways make sense, so a hard-line rule doesn't seem necessary to me.

**Comment by evanthegrayt** [comment]
Done with https://github.com/publicstrategies/rubocop-config/commit/f3fd82ae14a5f97c91764f4142a53a7f5579357e

**Comment by EduardoOrestes** [comment]
I vote Disabled.
